language: dart
dart:
  - dev
  - stable

dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer: --fatal-warnings --fatal-infos lib
  - dart_style

after_success:
  - pub global activate dart_coveralls
  - pub global run dart_coveralls report test/time_duration_test.dart